#!/bin/bash

usage() {
    cat <<EOF
Usage: mvseq [options] DIR

  -h, --help             shows this help menu
  -f, --find [pat]       only rename files with this pattern
  -p, --prefix [name]    prefix for all new filenames
  -s, --suffix [name]    suffix/extension for all new filenames
  -z, --padzeros         pad the new filenames with zeros
  -l, --padlen [num]     padding length
  -i, --start [num]      start sequence at number (default 1)
  -v, --verbose          verbose mode
EOF
}

options=$(getopt -n mvseq -o hf:p:s:zl:i:v --long help,find:,prefix:,suffix:,padzeros,padlen:,start:,verbose -- "$@")
eval set -- "$options"

findexpr="*"
prefixfname=""
suffixfname=""
padzeros="n"
padlen=3
startseq=1
verbose=0

while true; do
    case "$1" in
        -h | --help)
            usage ; exit 0 ;;
        -f | --find)
            findexpr="$2"
            shift 2 ;;
        -p | --prefix)
            prefixfname="$2"
            shift 2 ;;
        -s | --suffix)
            suffixfname="$2"
            shift 2 ;;
        -z | --padzeros)
            padzeros="y"
            shift ;;
        -l | --padlen)
            padlen="$2"
            shift 2 ;;
        -i | --start)
            startseq="$2"
            shift 2 ;;
        -v | --verbose)
            verbose=1
            shift ;;
        --) shift; break ;;
    esac
done

mvargs=()

[ $verbose -ge 1 ] && mvargs+=("-v")

if [ $# -eq 0 ]; then
    usage
    exit
fi

build_name() {
    local counter="$1"

    local newf="$directory/$prefixfname"
    if [ "$padzeros" = "y" ]; then
        newf="${newf}$(printf "%0${padlen}d" "$counter")"
    else
        newf="${newf}$(printf "%d" "$counter")"
    fi

    echo "${newf}${suffixfname}"
}

#strip trailing slash
directory="${1%/}"

sessionprefix="mvseq-$(date +'%s')."
counter=$startseq

find "$directory" -maxdepth 1 -type f -name "$findexpr" -print0 | sort -zV | while IFS= read -r -d '' fname; do
    tmpname="${sessionprefix}${counter}"
    mv ${mvargs[@]} -- "$fname" "${directory}/${tmpname}"
    ((counter++))
done

counter=$startseq

find "$directory" -maxdepth 1 -type f -name "${sessionprefix}*" -print0 | sort -zV | while IFS= read -r -d '' fname; do
    mv ${mvargs[@]} -- "$fname" "$(build_name "$counter")"
    ((counter++))
done
